import {test} from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';
function engine(){
 const nodes=[],timeouts=new Map(),preferences=new Map();let next=1;
 function param(value=0){return {value,cancelScheduledValues(){},setValueAtTime(v){this.value=v},linearRampToValueAtTime(v){this.value=v}}}
 function node(type){const n={kind:type,type,gain:param(1),frequency:param(),Q:param(),detune:param(),started:false,stopped:false,connect(){},disconnect(){},start(){assert.equal(this.started,false,'A source was started twice');this.started=true},stop(){this.stopped=true}};nodes.push(n);return n}
 class Context{constructor(){this.sampleRate=100;this.currentTime=0;this.state='running';this.destination={}}createGain(){return node('gain')}createAnalyser(){return {...node('analyser'),frequencyBinCount:64}}createBuffer(){return {getChannelData(){return new Float32Array(200)}}}createBufferSource(){return node('source')}createOscillator(){return node('oscillator')}createBiquadFilter(){return node('filter')}}
 const html=readFileSync(new URL('../src/index.html',import.meta.url),'utf8');const script=html.slice(html.indexOf("'use strict';"),html.indexOf('/* ================= UI ================= */'))+'\nglobalThis.audio=AE;globalThis.rooms=MOOD_ORDER;';
 const ctx={window:{AudioContext:Context},localStorage:{getItem(k){return preferences.get(k)||null},setItem(k,v){preferences.set(k,v)}},document:{getElementById(){return null}},setTimeout(cb){const id=next++;timeouts.set(id,cb);return id},clearTimeout(id){timeouts.delete(id)},setInterval(){return next++},clearInterval(){},endSession(){},toast(){},Date,Math};vm.runInNewContext(script,ctx);return {audio:ctx.audio,rooms:ctx.rooms,nodes,timeouts,preferences};
}
test('every audible source starts exactly once in all four rooms',()=>{for(const slug of engine().rooms){const {audio,nodes}=engine();audio.play(slug);const sources=nodes.filter(n=>['source','oscillator'].includes(n.kind));assert.ok(sources.length>=3);assert.ok(sources.every(n=>n.started));assert.equal(audio.playing,true)}});
test('pausing tears down every sound and modulation source',()=>{const {audio,nodes,timeouts}=engine();audio.play('golden-hour');audio.pause(true);for(const callback of timeouts.values())callback();assert.ok(nodes.filter(n=>['source','oscillator'].includes(n.kind)).every(n=>n.stopped));assert.equal(audio.playing,false)});
test('new playback cancels an earlier finishing timer',()=>{const {audio,timeouts}=engine();audio.play('deep-focus');audio.finishTimer();const finishing=audio.finishId;assert.ok(timeouts.has(finishing));audio.play('rainy-window');assert.equal(timeouts.has(finishing),false);assert.equal(audio.playing,true);assert.equal(audio.master.gain.value,.8)});
test('pausing cancels pending fade completion and clears timer state',()=>{const {audio,timeouts}=engine();audio.play('deep-focus');audio.finishTimer();const finishing=audio.finishId;audio.pause();assert.equal(timeouts.has(finishing),false);assert.equal(audio.endsAt,0)});
test('editing a paused room saves its own layers before playback',()=>{const {audio}=engine();audio.setLayer('rain',false,.6,'rainy-window');audio.play('rainy-window');assert.equal(audio.live.rain.on,false);assert.equal(audio.live.rain.vol,.6)});
test('editing a different room does not change the currently playing room',()=>{const {audio}=engine();audio.play('midnight-drive');const original=audio.live.rain.vol;audio.setLayer('rain',false,.9,'rainy-window');assert.equal(audio.live.rain.on,true);assert.equal(audio.live.rain.vol,original)});
