import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';
const source=readFileSync(new URL('../src/product.js',import.meta.url),'utf8');
function setup(consent=false,privacy={}){
 const prefs=new Map([['usageConsent',consent]]),events=[],timers=[],navigations=[];
 const audio={playing:false,pause(){this.playing=false}},moods={'deep-focus':{},'golden-hour':{},'rainy-window':{}};
 const ctx=vm.createContext({store:{get:(k,d)=>prefs.has(k)?prefs.get(k):d,set:(k,v)=>prefs.set(k,v)},navigator:privacy,crypto,structuredClone,Date,MOODS:moods,AE:audio,history:{pushState(_,__,url){navigations.push(url)}},route(){},$(){return {click(){audio.playing=true}}},app:{querySelector(selector){return {click(){timers.push(selector)}}}},fetch:async(_,data)=>{events.push(JSON.parse(data.body));return {}},toast(){}});
 vm.runInContext(source.slice(source.indexOf('const QUICK_STARTS='),source.indexOf('async function Insights()')),ctx);return {ctx,prefs,events,timers,navigations,audio};
}
test('study starts synchronously with the intended room, mix and 25-minute timer',()=>{const h=setup();vm.runInContext("startListening(QUICK_STARTS.study.mood,QUICK_STARTS.study)",h.ctx);assert.equal(h.audio.playing,true);assert.deepEqual(h.navigations,['#/studio/deep-focus']);assert.deepEqual(h.timers,['[data-min="25"]']);assert.equal(h.prefs.get('layers:deep-focus').restraint.on,false);assert.equal(h.prefs.get('vol'),.65)});
test('wind-down and rain presets keep the correct layers and timer choices',()=>{const h=setup();vm.runInContext("startListening(QUICK_STARTS.unwind.mood,QUICK_STARTS.unwind)",h.ctx);assert.deepEqual(h.timers,['[data-min="15"]']);vm.runInContext("startListening(QUICK_STARTS.rain.mood,QUICK_STARTS.rain)",h.ctx);const rain=h.prefs.get('layers:rainy-window');assert.equal(rain.rain.on,true);assert.equal(rain.drone.on,false);assert.equal(rain.atmos.on,false);assert.equal(h.timers.length,1)});
test('analytics opt-out, Do Not Track and Global Privacy Control send no events',()=>{for(const [consent,privacy]of [[false,{}],[true,{doNotTrack:'1'}],[true,{globalPrivacyControl:true}]]){const h=setup(consent,privacy);vm.runInContext("trackEvent('play','deep-focus');trackVisit()",h.ctx);assert.equal(h.events.length,0);assert.equal(h.prefs.has('usageVisitDay'),false)}});
test('opted-in visits count once per device day and record a return on a later day',()=>{const h=setup(true);assert.equal(h.events.length,1);vm.runInContext('trackVisit()',h.ctx);assert.equal(h.events.length,1);h.prefs.set('usageVisitDay','2020-01-01');vm.runInContext('trackVisit()',h.ctx);assert.deepEqual(h.events.map(e=>e.event),['visit','visit','return']);assert.equal('email' in h.events[0],false)});
