/* Cloud studio, subscription surfaces, and accessible dialogs. */
let cloud={user:null,plus:false,billingReady:false},cloudError='',session=null,cloudLoading=true;
const FREE_ROOMS=[...MOOD_ORDER];
const TEASERS=[['ocean-dusk','Ocean Dusk','The shore has nothing to ask of you.','ocean'],['forest-floor','Forest Floor','A clearing between everything else.','forest'],['velvet-night','Velvet Night','Let the day dissolve into the dark.','velvet'],['ember-room','Ember Room','A little warmth. A little less hurry.','ember']];
const escapeHTML=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function requestAPI(path,method='GET',body){const response=await fetch('/api/'+path,{method,credentials:'same-origin',headers:method==='GET'?{}:{'Content-Type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)})});const data=await response.json();if(!response.ok)throw new Error(data.error||'Please try again.');return data}
function loginLink(text='Sign in with ChatGPT'){return '<a class="btn primary" href="/signin-with-chatgpt?return_to='+encodeURIComponent('/#/account')+'" target="_top">'+text+'</a>'}
async function initCloud(){
 try{cloud=await requestAPI('me');cloudError='';Object.entries(cloud.rooms||{}).forEach(([slug,mood])=>{MOODS[slug]=mood;if(!MOOD_ORDER.includes(slug))MOOD_ORDER.push(slug)});}
 catch(error){cloudError=error.message;}finally{cloudLoading=false;const r=location.hash;if(r.includes('/account')||r.includes('/saved')||r.includes('/pricing')||r.includes('/explore')||TEASERS.some(t=>r.includes(t[0])))route();}
 if(new URLSearchParams(location.search).get('checkout')==='success'){history.replaceState(null,'',location.pathname+'#/account');toast('Checkout returned. Access updates after payment verification.');if(!cloud.plus){let tries=0;const poll=setInterval(async()=>{tries++;try{const next=await requestAPI('me');if(next.plus){cloud=next;Object.assign(MOODS,next.rooms);Object.keys(next.rooms).forEach(s=>{if(!MOOD_ORDER.includes(s))MOOD_ORDER.push(s)});route();toast('Welcome to AFTERGLOW Plus.');clearInterval(poll)}}catch{}if(tries>=8)clearInterval(poll)},3000)}}
}
const nativePlay=AE.play.bind(AE),nativePause=AE.pause.bind(AE);
AE.play=function(slug){if(session)endSession();nativePlay(slug);if(this.playing)session={id:crypto.randomUUID(),mood:slug,started:Date.now()};};
AE.pause=function(fast){endSession();nativePause(fast)};
function endSession(){if(!session)return;const ended=session;session=null;const seconds=Math.min(21600,Math.floor((Date.now()-ended.started)/1000));if(cloud.user&&seconds>=10)requestAPI('sessions','POST',{id:ended.id,mood:ended.mood,seconds}).catch(()=>toast('Session history could not sync. Your sound settings stay on this device.'))}
addEventListener('pagehide',()=>{if(!session||!cloud.user)return;const seconds=Math.min(21600,Math.floor((Date.now()-session.started)/1000));if(seconds>=10)fetch('/api/sessions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:session.id,mood:session.mood,seconds}),keepalive:true}).catch(()=>{});session=null;});
function showDialog(title,description,content,onSubmit){
 document.querySelector('dialog')?.remove();const dialog=document.createElement('dialog');dialog.innerHTML='<form><h2>'+escapeHTML(title)+'</h2><p>'+escapeHTML(description)+'</p>'+content+'<p class="statusline" role="alert"></p><div class="actions"><button class="btn primary" type="submit">Confirm</button><button class="btn ghost" type="button" data-close>Cancel</button></div></form>';document.body.append(dialog);dialog.querySelector('[data-close]').onclick=()=>dialog.close();dialog.addEventListener('close',()=>dialog.remove());dialog.querySelector('form').onsubmit=async e=>{e.preventDefault();const b=dialog.querySelector('[type=submit]');b.disabled=true;try{await onSubmit(dialog);dialog.close()}catch(error){dialog.querySelector('[role=alert]').textContent=error.message;b.disabled=false}};dialog.showModal();
}
function wireExtras(slug){
 $('#savemix').onclick=()=>{
 if(!cloud.user){toast('Sign in to save custom mixes across devices.');location.hash='/account';return}
 showDialog('Keep this feeling.','Your room, volume and all three layers will be saved to your account.','<label class="field" for="mixname">Mix name</label><input class="text" id="mixname" name="mixname" maxlength="60" required placeholder="My evening ritual" autocomplete="off">',async dialog=>{
 const layers={};MOODS[slug].layers.forEach(([id,,def])=>{const prefs=store.get('layers:'+slug,{})[id];layers[id]={on:prefs?.on!==false,vol:prefs?.vol??def}});
 await requestAPI('mixes','POST',{name:dialog.querySelector('input').value,mood:slug,settings:{volume:store.get('vol',.8),layers}});toast('Custom mix saved to your cloud library.');});
 };
 $('#fullscreen').onclick=()=>{document.body.classList.add('immersive');$('.stage').onclick=exitImmersive};
}
function exitImmersive(){document.body.classList.remove('immersive');const stage=$('.stage');if(stage)stage.onclick=null}
addEventListener('keydown',event=>{if(event.key==='Escape')exitImmersive();if(event.code==='Space'&&currentRoute.startsWith('studio/')&&!document.querySelector('dialog')&&!['INPUT','BUTTON','A','TEXTAREA','SELECT'].includes(document.activeElement.tagName)){event.preventDefault();$('#playbtn')?.click()}});
addEventListener('hashchange',exitImmersive);
function teasers(){return '<div class="plus-preview">'+TEASERS.map(([slug,name,desc,art])=>'<article><a href="'+(cloud.plus?'#/studio/'+slug:'#/pricing')+'"><div class="art"><div class="art-'+art+'"></div></div><h3>'+name+'</h3><p class="bodycopy">'+desc+'</p><span class="badge">'+(cloud.plus?'Enter room ↗':'Plus room')+'</span></a></article>').join('')+'</div>'}
const originalExplore=Explore;
Explore=function(){originalExplore();if(!cloud.plus){const section=document.createElement('section');section.className='section';section.innerHTML='<div class="section-head"><h2 class="display">A little <em>further.</em></h2><a class="btn ghost" href="#/pricing">Explore Plus</a></div>'+teasers();app.querySelector('footer').before(section)}};
function Pricing(){
 setActiveNav('pricing');app.innerHTML='<section class="page"><span class="eyebrow">Afterglow Plus</span><h1>More room.<br>Same <em>quiet.</em></h1><p class="lead">Start with a free studio you can keep. Choose Plus when your daily ritual needs more space.</p><div class="billing-switch" role="group" aria-label="Billing period"><button data-period="monthly" aria-pressed="true">Monthly</button><button data-period="yearly" aria-pressed="false">Yearly · save 33%</button></div><div class="plans"><article class="plan"><span class="eyebrow">Your everyday studio</span><h2>Free</h2><p class="price">$0<span> / always</span></p><ul><li>Four original atmosphere rooms</li><li>Independent sound layers and focus timers</li><li>Unlimited listening, without advertising</li><li>Three cloud mixes when you sign in</li><li>Seven days of session history</li></ul><a class="btn ghost" href="#/studio/deep-focus">Enter the free studio</a></article><article class="plan plus"><span class="eyebrow">For the rituals you return to</span><h2>Plus</h2><p class="price" id="plusprice">$3<span> / month</span></p><p class="bodycopy" id="billdetail">Billed monthly. Cancel future renewals in your billing portal.</p><ul><li>All eight atmosphere rooms</li><li>Up to 200 custom cloud mixes</li><li>One year of session history</li><li>Your studio library across devices</li><li>Self-service billing and cancellation</li></ul><button class="btn primary" id="upgrade">'+(cloud.plus?'Manage your subscription':cloud.billingReady?'Choose Plus':'Plus is coming soon')+'</button><p class="statusline" id="billstatus" role="status">'+(cloud.billingReady?'Prices in USD. Applicable tax is shown at checkout.':'The free studio is open. Paid subscriptions are not on sale yet.')+'</p></article></div><h2 class="display">Four more ways to <em>settle.</em></h2>'+teasers()+'<details><summary>Will the free rooms stay free?</summary><p>Yes. All four original rooms, their sound layers and timers belong to the Free plan. You can listen without a subscription.</p></details><details><summary>What happens if I cancel?</summary><p>Cancel future renewals from Manage billing. Plus access continues through your paid period. After it ends, Free limits apply. Existing mixes remain available to view and delete; Plus rooms require an active subscription to open.</p></details><details><summary>Is this recorded music?</summary><p>No. AFTERGLOW creates original ambient textures using your browser’s sound engine. Suggested artist links open a separate service; we do not stream or sell their recordings.</p></details><details><summary>Can I listen on my phone?</summary><p>Yes. Tap Play to start. Mobile browsers can suspend audio when the device locks or the tab goes into the background. Keep the studio open for a dependable session.</p></details></section>'+FOOT;
 let interval='monthly';app.querySelectorAll('[data-period]').forEach(b=>b.onclick=()=>{interval=b.dataset.period;app.querySelectorAll('[data-period]').forEach(x=>x.setAttribute('aria-pressed',x===b));$('#plusprice').innerHTML=interval==='monthly'?'$3<span> / month</span>':'$24<span> / year</span>';$('#billdetail').textContent=interval==='monthly'?'Billed monthly. Cancel future renewals in your billing portal.':'$24 charged once a year. Equivalent to $2/month. Cancel future renewals anytime.'});
 $('#upgrade').onclick=async()=>{
 if(!cloud.billingReady){toast('Plus is not on sale yet. Enjoy the free studio.');return}
 if(!cloud.user){location.hash='/account';return}
 const button=$('#upgrade');button.disabled=true;try{const response=await requestAPI(cloud.plus?'billing/portal':'billing/checkout','POST',cloud.plus?{}:{interval});location.assign(response.url)}catch(error){$('#billstatus').textContent=error.message;button.disabled=false}
 };
}
function Account(){
 setActiveNav('account');
 if(cloudLoading){app.innerHTML='<section class="empty"><h2>Opening your studio…</h2></section>';return}
 if(cloudError){app.innerHTML='<section class="empty"><h2>Cloud studio is unavailable.</h2><p class="bodycopy">'+escapeHTML(cloudError)+'</p><button class="btn ghost" id="retrycloud">Try again</button><a class="btn primary" href="#/studio/deep-focus">Use the free studio</a></section>';$('#retrycloud').onclick=()=>{cloudLoading=true;Account();initCloud()};return}
 if(!cloud.user){app.innerHTML='<section class="empty"><span class="eyebrow">Your personal studio</span><h2>Keep the sounds<br><strong>you come back to.</strong></h2><p class="bodycopy" style="max-width:48ch">Sign in to keep custom mixes across devices and see your listening sessions. Your four free rooms are always here.</p>'+loginLink()+'<a class="btn ghost" href="#/studio/deep-focus">Keep listening without an account</a></section>'+FOOT;return}
 app.innerHTML='<section class="page"><span class="eyebrow">Your studio account</span><h1>A place to <em>return.</em></h1><p class="lead">'+escapeHTML(cloud.user.email)+' · '+(cloud.plus?'Plus studio':'Free studio')+'</p><div class="account-grid"><article class="panel"><h2>Your membership</h2><p>'+membershipCopy()+'</p><a class="btn ghost" href="#/pricing">'+(cloud.plus?'Compare plans':'Discover Plus')+'</a> '+(cloud.subscription?'<button class="act" id="portal">Manage billing</button>':'')+'<p class="statusline" id="accountstatus" role="status"></p></article><article class="panel"><h2>Your data, your choice</h2><p>Export your mixes and session history, or delete your AFTERGLOW account data.</p><button class="act" id="export">Export data</button> <button class="act danger" id="deleteaccount">Delete account data</button><p class="statusline">Deletion removes AFTERGLOW data. It does not delete your ChatGPT account.</p></article><article class="panel" style="grid-column:1/-1"><h2>Your recent rhythm</h2><div id="history"><p>Loading your sessions…</p></div></article></div><div class="actions" style="margin-top:2rem"><a class="btn primary" href="#/saved">Open your library</a><a class="btn ghost" href="/signout-with-chatgpt?return_to=%2F" target="_top">Sign out</a></div></section>'+FOOT;
 if($('#portal'))$('#portal').onclick=async()=>{try{const result=await requestAPI('billing/portal','POST',{});location.assign(result.url)}catch(error){$('#accountstatus').textContent=error.message}};
 $('#export').onclick=async()=>{try{const data=await requestAPI('export');const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='afterglow-data.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch(error){toast(error.message)}};
 $('#deleteaccount').onclick=()=>showDialog('Delete your studio data?','This permanently removes your custom mixes and session history. An active subscription must end first.','<label class="field" for="deleteconfirm">Type DELETE to confirm</label><input class="text" id="deleteconfirm" required pattern="DELETE" autocomplete="off">',async()=>{await requestAPI('account','DELETE',{});toast('Your studio data has been deleted.');location.assign('/signout-with-chatgpt?return_to=%2F')});
 const holder=$('#history');requestAPI('sessions').then(data=>{if(!holder.isConnected)return;if(!data.sessions.length){holder.innerHTML='<p>Your next quiet moment starts here. Sessions of at least 10 seconds appear after you pause or finish.</p><a class="act" href="#/studio/deep-focus">Start a session</a>';return}const minutes=Math.round(data.sessions.reduce((sum,row)=>sum+row.seconds,0)/60);holder.innerHTML='<div class="stats"><div><strong>'+minutes+'</strong><small>listening minutes</small></div><div><strong>'+data.sessions.length+'</strong><small>sessions · last '+data.days+' days</small></div></div>'+data.sessions.slice(0,20).map(row=>'<div class="history-row"><strong>'+escapeHTML(MOODS[row.mood]?.name||roomName(row.mood))+'</strong><span>'+Math.max(1,Math.round(row.seconds/60))+' min · '+new Date(row.created_at).toLocaleDateString()+'</span></div>').join('')}).catch(error=>{if(holder.isConnected)holder.innerHTML='<p>'+escapeHTML(error.message)+'</p>'});
}
function membershipCopy(){if(!cloud.subscription)return 'Four free rooms, three cloud mixes, and a week of session history. No card needed.';const sub=cloud.subscription;if(cloud.plus)return (sub.cancelAtPeriodEnd?'Your subscription ends on ':'Your next renewal is on ')+new Date(sub.periodEnd*1000).toLocaleDateString()+'.';return 'Subscription status: '+escapeHTML(sub.status)+'. Your free studio remains available. Use the billing portal to review payment details.'}
function roomName(slug){return TEASERS.find(row=>row[0]===slug)?.[1]||MOODS[slug]?.name||slug}
function Library(){
 Saved();app.querySelector('footer')?.remove();const section=document.createElement('section');section.className='section';section.innerHTML='<div class="section-head"><h2 class="display">Your custom <em>mixes</em></h2><p class="section-note">'+(cloud.plus?'200 cloud mix spaces':'Three free cloud mix spaces')+'</p></div><div id="cloudmixes">'+(cloudLoading?'<p class="bodycopy">Loading your studio…</p>':cloudError?'<p class="bodycopy">Cloud library is unavailable. Your device favourites are above.</p>':cloud.user?'<p class="bodycopy">Opening your cloud library…</p>':'<p class="lead">Save the exact balance of a room’s sounds, then open it on any device.</p>'+loginLink())+'</div>';app.append(section);app.insertAdjacentHTML('beforeend',FOOT);
 if(!cloud.user)return;const holder=$('#cloudmixes');requestAPI('mixes').then(data=>{if(!holder.isConnected)return;if(!data.mixes.length){holder.innerHTML='<p class="lead">No custom mixes yet. Shape a room’s sound, then choose Save custom mix.</p><a class="btn ghost" href="#/studio/deep-focus">Create your first mix</a>';return}
 holder.innerHTML='<div class="saved-grid">'+data.mixes.map(mix=>'<article class="saved-card"><span class="eyebrow">'+escapeHTML(roomName(mix.mood))+'</span><h3>'+escapeHTML(mix.name)+'</h3><span class="statusline">'+new Date(mix.created_at).toLocaleDateString()+'</span><button class="act" data-load="'+escapeHTML(mix.id)+'">'+(mix.locked?'Requires Plus':'Open mix')+'</button><button class="rm" data-delete="'+escapeHTML(mix.id)+'">Delete mix</button></article>').join('')+'</div>';
 holder.querySelectorAll('[data-load]').forEach(b=>b.onclick=()=>{const mix=data.mixes.find(m=>m.id===b.dataset.load);if(mix.locked){location.hash='/pricing';return}store.set('vol',mix.settings.volume);store.set('layers:'+mix.mood,mix.settings.layers);if(location.hash==='#/studio/'+mix.mood)route();else location.hash='/studio/'+mix.mood;toast('Mix loaded. Press Play when you’re ready.')});
 holder.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>showDialog('Delete this mix?','This removes the mix from your cloud library.','',async()=>{await requestAPI('mixes/'+b.dataset.delete,'DELETE',{});Library();toast('Mix deleted.')}));
 }).catch(error=>{if(holder.isConnected)holder.innerHTML='<p class="bodycopy">'+escapeHTML(error.message)+'</p>'});
}
function Info(type){
 const content={
 help:['A little guidance.','<h2>Start in three steps</h2><p>Open a room, press Play, and adjust the three sound layers. Your volume and layer preferences stay on this device. Use headphones at a comfortable volume.</p><h2>Make a focus session</h2><p>Choose a timer to start listening immediately. The sound fades out when time is up. Pausing ends the current timer; you can choose a fresh one when you return. Press Space in a room to play or pause.</p><h2>Save and return</h2><p>Save a room as a device favourite with the heart button. Sign in and use Save custom mix to store the exact sound balance in your cloud library.</p><h2>Audio or cloud trouble?</h2><p>Sound needs a tap or click to start. If you cannot hear anything, check your device volume and layer switches. Mobile devices may suspend background sound. If a cloud request fails, try again later; the free rooms still work.</p><h2>Billing</h2><p>When Plus is available, checkout confirms the billing interval and amount. Account → Manage billing opens the secure portal for payment updates and cancellation. Access is granted after the provider verifies your subscription.</p>'],
 privacy:['Your quiet. Your privacy.','<p>Effective 8 October 2026. This page describes the current AFTERGLOW service.</p><h2>What we store</h2><p>When you sign in, we store your site-specific account ID and email address, custom mixes, listening duration and room names, and subscription references. We do not record microphone audio. We do not store card numbers.</p><h2>Device preferences</h2><p>Your volume, layer preferences, last room and saved room favourites use your browser’s local storage. Clearing site data removes these device preferences.</p><h2>Services involved</h2><p>ChatGPT provides sign-in and site access. Hosting and cloud data run on the platform’s Cloudflare infrastructure. Google Fonts receives font requests including network information such as your IP address. Artist links open YouTube only when you choose them. If billing is enabled, Stripe processes payments under its own privacy policy.</p><h2>Purpose and retention</h2><p>We use account records to run your studio and enforce your subscription. Records remain until you delete your studio data; history views show seven days for Free and one year for Plus. A limited billing event ledger and payment provider records may remain for reconciliation and financial obligations.</p><h2>Your choices</h2><p>Use Account → Export data to download your studio records. Use Delete account data to remove mixes, sessions and your AFTERGLOW account record. Active subscriptions must end first. Deletion does not delete your ChatGPT account or the payment provider’s records.</p><h2>Analytics</h2><p>This version includes no advertising trackers or third-party analytics scripts. Hosting providers may retain operational and security logs.</p>'],
 terms:['The studio, clearly.','<p>Effective 8 October 2026. By using AFTERGLOW, you agree to these service terms.</p><h2>The service</h2><p>AFTERGLOW generates original ambient sound in your browser for personal listening, focus and relaxation. It is not a medical service and makes no promises about health or productivity. Artist suggestions are external links; their music is not included in a subscription.</p><h2>Free and Plus</h2><p>Free includes four rooms, unlimited listening, three cloud mixes and seven days of visible history. Plus includes eight rooms, up to 200 cloud mixes and a year of visible history. Timers and local favourites are available on both plans.</p><h2>Subscription charges</h2><p>Subscriptions are not currently on sale. When enabled, Plus costs USD 3 monthly or USD 24 yearly, billed in advance. Any applicable tax is displayed before payment. The provider must confirm payment before paid access begins.</p><h2>Renewal and cancellation</h2><p>Subscriptions renew at the selected interval unless you cancel future renewals through the billing portal. Paid access continues until the current period ends. Failed payments may suspend Plus features. Free rooms remain available.</p><h2>Refunds and your rights</h2><p>Charges, disputes and refund requests are reviewed through the merchant’s support channel. Statutory consumer rights apply. The service does not automatically issue refunds.</p><h2>Responsible use</h2><p>Keep your account secure. Do not attempt to access another person’s library, bypass subscription controls, overload the service, or redistribute the service as your own product.</p><h2>Availability</h2><p>Browser restrictions, network interruptions and maintenance can affect sound and cloud features. We provide the service as available, subject to rights that applicable law does not allow us to exclude.</p><h2>Before paid launch</h2><p>The operating merchant’s legal identity, support contact and applicable billing policies will be supplied before paid subscriptions are enabled.</p>']
 };
 setActiveNav('');const [title,body]=content[type];app.innerHTML='<section class="page info-content"><span class="eyebrow">AFTERGLOW / '+type+'</span><h1>'+title+'</h1>'+body+'<a class="btn ghost" href="#/">Return to the studio</a></section>'+FOOT;
}
